= Gib niemals auf
Klaus Baldermann <klaus@soonix.de>

[[Feenlied]]
[verse, Klaus Baldermann 2010, Lied der Fee im Musical 
http://www.musikschule-baldermann.de/archiv/8-musikschule/3-musical-aschenputtel-am-24-und-25-april-2010[Aschenputtel]]
____
Glaube stets daran,
dein Weg mag schwer dir scheinen,
fällst du dann und wann,
willst du auch manchmal weinen,
doch du weißt, es kann
im Großen wie im Kleinen
nichts dir widerstehn:
Gib niemals auf!

Hoffe nur darauf,
dein Weg ist schon bereitet,
scheint es manchmal auch,
daß er dich irreleitet
doch du kommst ans Ziel
wenn du nur tapfer schreitest
drum vergiß es nie:
Gib niemals auf!

Gib niemals auf
denn du bist nicht allein,
zur rechten Zeit
wirst du am Ziele sein,
gib niemals auf,
auf deinem Weg wird immer dir ein Freund zur Seite stehen
du kommst ans Ziel, du wirst es sehen!
du bist nicht allein, gib niemals auf.

Liebe ist das Wort,
das Zauberwort des Lebens.
Sie ist der Akkord,
die Melodie des Gebens,
die Begleitmusik,
der Klang, mit dem du findest,
was so lang gefehlt...
Gib niemals auf!
____
